apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"notice-service"},"name":"notice-service","namespace":"bravo-core-ns"},"spec":{"ports":[{"name":"http","port":3003,"targetPort":3003}],"selector":{"app":"notice-service"}}}
  labels:
    app: notice-service
  name: notice-service
  namespace: bravo-core-ns
spec:
  clusterIP: 10.233.48.145
  clusterIPs:
    - 10.233.48.145
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: notice-service
  sessionAffinity: None
  type: ClusterIP
