apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"community-service"},"name":"community-service","namespace":"bravo-core-ns"},"spec":{"ports":[{"name":"http","port":3002,"targetPort":3002}],"selector":{"app":"community-service"}}}
  labels:
    app: community-service
  name: community-service
  namespace: bravo-core-ns
spec:
  clusterIP: 10.233.2.69
  clusterIPs:
    - 10.233.2.69
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: community-service
  sessionAffinity: None
  type: ClusterIP
