apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ai-service"},"name":"ai-service","namespace":"bravo-ai-integration-ns"},"spec":{"ports":[{"name":"http","port":3009,"targetPort":3009}],"selector":{"app":"ai-service"}}}
  labels:
    app: ai-service
  name: ai-service
  namespace: bravo-ai-integration-ns
spec:
  clusterIP: 10.233.33.196
  clusterIPs:
    - 10.233.33.196
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3009
      protocol: TCP
      targetPort: 3009
  selector:
    app: ai-service
  sessionAffinity: None
  type: ClusterIP
