apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"stamp-service"},"name":"stamp-service","namespace":"bravo-core-ns"},"spec":{"ports":[{"name":"http","port":3010,"targetPort":3010}],"selector":{"app":"stamp-service"}}}
  labels:
    app: stamp-service
  name: stamp-service
  namespace: bravo-core-ns
spec:
  clusterIP: 10.233.6.115
  clusterIPs:
    - 10.233.6.115
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3010
      protocol: TCP
      targetPort: 3010
  selector:
    app: stamp-service
  sessionAffinity: None
  type: ClusterIP
