apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-role
  namespace: bravo-ai-integration-ns
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get"]

