apiVersion: v1
kind: Secret
metadata:
  name: bravo-secrets
  namespace: bravo-core-ns
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA5V6I7LE6QMTPKOEO"
  AWS_SECRET_ACCESS_KEY: "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"
  KAKAO_REST_API_KEY: "75218448ddb01cb67aec079a8dbd61ae"
  KAKAO_CLIENT_SECRET: "jqAC1gVOlf7cBhb500rReivNfJ3o5F59"
  NAVER_CLIENT_ID: "bPUAgB6QZBRBZrL3G1CN"
  NAVER_CLIENT_SECRET: "9TzCuTvpBJ"
  JWT_SECRET: "your-jwt-secret-here"
  VITE_CESIUM_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4MTI5Mjc1ZC02YjhjLTRhOWMtYTQyNS03NjkwYzgyZGMyZTYiLCJpZCI6MzY3NTE0LCJpYXQiOjE3NjUxNjExNTF9.As5RoX8zHf_k32QISU3-3xnvDi_VWt9rxOmgCfIFDwM"
  BEDROCK_AGENT_ID: "HRBRQBVKNU"
  BEDROCK_AGENT_ALIAS_ID: "PQJEHEXUOU"
  BEDROCK_COURSE_AGENT_ID: "EFHTPK8I6B"
  BEDROCK_COURSE_AGENT_ALIAS_ID: "MJCYLWVRGW"
  VITE_EQUIPMENT_AGENT_ID: "83IGSWEO23"
  VITE_EQUIPMENT_ALIAS_ID: "3VAJWBOVYR"

