apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"chatbot-service"},"name":"chatbot-service","namespace":"bravo-ai-integration-ns"},"spec":{"ports":[{"name":"http","port":3007,"targetPort":3007}],"selector":{"app":"chatbot-service"}}}
  labels:
    app: chatbot-service
  name: chatbot-service
  namespace: bravo-ai-integration-ns
spec:
  clusterIP: 10.233.47.140
  clusterIPs:
    - 10.233.47.140
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3007
      protocol: TCP
      targetPort: 3007
  selector:
    app: chatbot-service
  sessionAffinity: None
  type: ClusterIP
