apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio-to-frontend
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      istio: ingressgateway
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: bravo-front-ns
    ports:
    - protocol: TCP
      port: 80

