apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ai-infra-service","namespace":"bravo-ai-integration-ns"},"spec":{"ports":[{"name":"http","port":3011,"targetPort":3011}],"selector":{"app":"ai-infra-service"},"type":"ClusterIP"}}
  name: ai-infra-service
  namespace: bravo-ai-integration-ns
spec:
  clusterIP: 10.233.42.149
  clusterIPs:
    - 10.233.42.149
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3011
      protocol: TCP
      targetPort: 3011
  selector:
    app: ai-infra-service
  sessionAffinity: None
  type: ClusterIP
bravo@master1:~/LABs/application_cd/ai-integration/ai-infra-service$ cat service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ai-infra-service","namespace":"bravo-ai-integration-ns"},"spec":{"ports":[{"name":"http","port":3011,"targetPort":3011}],"selector":{"app":"ai-infra-service"},"type":"ClusterIP"}}
  name: ai-infra-service
  namespace: bravo-ai-integration-ns
spec:
  clusterIP: 10.233.42.149
  clusterIPs:
    - 10.233.42.149
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3011
      protocol: TCP
      targetPort: 3011
  selector:
    app: ai-infra-service
  sessionAffinity: None
  type: ClusterIP
