apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"store-service"},"name":"store-service","namespace":"bravo-core-ns"},"spec":{"ports":[{"name":"http","port":3006,"targetPort":3006}],"selector":{"app":"store-service"}}}
  labels:
    app: store-service
  name: store-service
  namespace: bravo-core-ns
spec:
  clusterIP: 10.233.22.204
  clusterIPs:
    - 10.233.22.204
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3006
      protocol: TCP
      targetPort: 3006
  selector:
    app: store-service
  sessionAffinity: None
  type: ClusterIP
