apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cr
rules:
# ===============================
# Cluster-scope READ (필수)
# ===============================
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
    - get
    - list
    - watch

# ===============================
# Namespace-scope WRITE (배포)
# ===============================
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
