apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-rb
  namespace: bravo-ai-integration-ns
subjects:
- kind: ServiceAccount
  name: ai-sa
  namespace: bravo-ai-integration-ns
roleRef:
  kind: Role
  name: ai-role
  apiGroup: rbac.authorization.k8s.io

