apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-manager-binding
  namespace: bravo-ai-integration-ns
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: bravo-platform-ns
roleRef:
  kind: Role
  name: argocd-app-manager
  apiGroup: rbac.authorization.k8s.io

