apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rb
  namespace: bravo-front-ns
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: bravo-front-ns
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io

