apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rb
  namespace: bravo-monitoring-ns
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: bravo-monitoring-ns
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io

