apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-rb
  namespace: bravo-efk-ns
subjects:
- kind: ServiceAccount
  name: efk-sa
  namespace: bravo-efk-ns
roleRef:
  kind: Role
  name: kibana-role
  apiGroup: rbac.authorization.k8s.io
