apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-rb
  namespace: bravo-mongo-ns
subjects:
- kind: ServiceAccount
  name: mongo-sa
  namespace: bravo-mongo-ns
roleRef:
  kind: Role
  name: mongo-role
  apiGroup: rbac.authorization.k8s.io

