apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rb
  namespace: bravo-redis-ns
subjects:
- kind: ServiceAccount
  name: redis-sa
  namespace: bravo-redis-ns
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io

