apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube-rb
  namespace: bravo-platform-ns
subjects:
- kind: ServiceAccount
  name: platform-sa
  namespace: bravo-platform-ns
roleRef:
  kind: Role
  name: sonarqube-role
  apiGroup: rbac.authorization.k8s.io

