apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-crb
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: bravo-platform-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-cr
