apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flagger-crb
subjects:
- kind: ServiceAccount
  name: platform-sa
  namespace: bravo-platform-ns
roleRef:
  kind: ClusterRole
  name: flagger-cr
  apiGroup: rbac.authorization.k8s.io
