apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-crb
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: bravo-monitoring-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-cr