apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-crb
subjects:
- kind: ServiceAccount
  name: istiod-sa
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio-cr
  apiGroup: rbac.authorization.k8s.io
