apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-crb
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: bravo-monitoring-ns
roleRef:
  kind: ClusterRole
  name: loki-cr
  apiGroup: rbac.authorization.k8s.io
