apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-crb
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: bravo-backup-ns
roleRef:
  kind: ClusterRole
  name: longhorn-cr
  apiGroup: rbac.authorization.k8s.io
