apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-crb
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  namespace: bravo-monitoring-ns
roleRef:
  kind: ClusterRole
  name: prometheus-cr
  apiGroup: rbac.authorization.k8s.io

