apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: frontend-serviceentry
  namespace: istio-system
spec:
  hosts:
  - frontend.bravo-front-ns.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL

