apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-core-to-ai
  namespace: bravo-ai-integration-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: bravo-core-ns
    ports:
    - protocol: TCP
      port: 3009   # ai-service
    - protocol: TCP
      port: 3007   # chatbot-service
    - protocol: TCP
      port: 3011   # ai-infra-service
